### ISSUE TITLE
systemd timer failed

### ISSUE THREAD

**Issue by killajoe** [manuel-192/antergos-reflector#3]
`systemctl status reflector-antergos
● reflector-antergos.service - Updates /etc/pacman.d/antergos-mirrorlist
   Loaded: loaded (/etc/systemd/system/reflector-antergos.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2018-11-29 19:36:11 CET; 1min 41s ago
  Process: 449 ExecStart=/usr/bin/reflector-antergos --save (code=exited, status=1/FAILURE)
 Main PID: 449 (code=exited, status=1/FAILURE)

Nov 29 19:36:10 empowered64 systemd[1]: Starting Updates /etc/pacman.d/antergos-mirrorlist...
Nov 29 19:36:11 empowered64 reflector-antergos[449]: Downloading latest mirror info ... ERROR: command 'wget -q -O fileinfo-449.html https://repo.antergos.info/antergos/x86_64/' failed.
Nov 29 19:36:11 empowered64 systemd[1]: reflector-antergos.service: Main process exited, code=exited, status=1/FAILURE
Nov 29 19:36:11 empowered64 systemd[1]: reflector-antergos.service: Failed with result 'exit-code'.
Nov 29 19:36:11 empowered64 systemd[1]: Failed to start Updates /etc/pacman.d/antergos-mirrorlist.`

`wget -q -O fileinfo-449.html https://repo.antergos.info/antergos/x86_64` works manually...

**Comment by manuel-192** [comment]
It is better use the remirror app instead of this.
However, the problem probably comes from a very slow response from that site.
